- js/views/comment.js
We were noticing that a page with comments was failing to render. There was also JS error on the page, which I thought might be the cause, and it was.
The error was:
> Cannot read property 'length' of null
And it was happening on this line in [`views/comment.js`](https://github.com/Automattic/o2/blob/cc022db37da7d1274cfc499a7f2ba0cff5a8c9ea/js/views/comment.js#L378):
```js
jsonifiedModel.isAnonymousAuthor = ( 0 === jsonifiedModel.userLogin.length ) && ( 0 === jsonifiedModel.noprivUserName.length );
```
It should be referring to `jsonifiedModel.currentUser.userLogin` instead of `jsonifiedModel.userLogin`.
> Fix anonymous author check by supplying missing currentUser property

- inc/tags.php
- inc/terms-in-comments.php
- inc/xposts.php
See https://make.wordpress.org/core/2015/07/02/deprecating-php4-style-constructors-in-wordpress-4-3/
> Eliminate PHP4-style constructors

- modules/to-do/load.php
Register taxonomy with `init` action and not before.
When not using the action, the global `wp` variable isn't set and taxonomy registration fails in various ways.
> Fix resolved taxonomy query, see #24

- js/utils/polling.js
Really long query strings break HTTP2 requests to nginx. I suspect there's an issue with the way a really long HTTP2 :path pseudo-header is handled in nginx, but I didn't root cause it that far.
The least impactful and simplest way to work around HTTP2 bug in nginx was to change the poll method to use POST instead of GET.
> This PR fixes the net::ERR_CONNECTION_CLOSED issue seen in browsers that support HTTP2.

- inc/read-api.php
- js/utils/polling.js
The current code produces a form-urlencoded string which contains an array of scripts[] and an array of styles[]. The form-urlencoded syntax necessitates that the array notation text be repeated for each item in the array, like so:
`scripts[]=jquery&scripts[]=jquery-core&scripts[]=jquery-migrate ... 
&
styles[]=bugout-css&styles[]=smileyproject&styles[]=follow_css ...
&`
This means that the use of the query string array notation translates to 10 bytes (scripts[]=) for each script and 7 bytes (styles[]=) for each style + the length of the actual value.
I was able to get a ~30%+ reduction in the size of the request by simply changing the structure of the data to a single variable for scripts and a single variable for styles, each of which hold a comma-delimited list of values, thus …
> O2 request size reduction

- js/app/main.js
- modules/live-comments/js/collections/items.js
- o2.php
This makes it so the post is only added to the live-comments widget if
the current view is not a preview solving #26.  Adds isPreview to
o2.options and to pageMeta.  There is a conditional check when adding an
item to the live-comments widget to prevent the post being added in a
preview state, while still a draft.  Let me know what tidying up the code needs, feedback is very appreciated!
> Fix-live-widget-#26

- js/collections/users.js
The userLogin field can contain illegal characters for css and so doesn't make a good choice to use as part of the modelClass css selector.
A hash is already part of the user object, so I updated the css selector to use it instead of userLogin.
> Changed modelClass to use hash instead of userLogin.

- inc/editor.php
- inc/keyboard.php
- inc/template-tags.php
- modules/checklists/load.php
- modules/filter-widget/load.php
- modules/follow/load.php
- modules/live-comments/load.php
- modules/notifications/load.php
- modules/offline/load.php
- modules/performance/inc/class-o2-basic-timers.php
- modules/performance/inc/class-o2-performance-monitor.php
- modules/performance/load.php
- modules/post-actions/load.php
- modules/recent-comments/load.php
- modules/sticky-posts/load.php
- modules/suggestions/load.php
- modules/to-do/inc/class-to-do-widget.php
- modules/to-do/load.php
- o2.php
This resolves several issues with the plugin folder being extra fragile from potentially being misnamed from `o2`  to something else.
Also adds some extra consistency within the project regarding the inclusion of files and adds some PHP 5.2 compat to boot by removing `__DIR__`
> Fix better asset routing

- inc/xposts.php
When there are no sites to xpost to (such as a single site install), there are PHP warnings thrown when using content such as `+1` in a post or comment. If the site returns PHP warnings, the user will get the black o2 error popup box. Make sure to use array_intersect on an array in `filter_xposts`. The warnings are:
`PHP Warning:  array_intersect(): Argument #2 is not an array in /wp-content/plugins/o2/inc/xposts.php on line 228`
`PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/o2/inc/terms-in-comments.php on line 36`
`PHP Warning:  array_intersect(): Argument #2 is not an array in /wp-content/plugins/o2/inc/xposts.php on line 228`
> Empty xposts array warning

- inc/template-tags.php
- modules/post-actions/load.php
Fixes #52.
The button should only be displayed if comment registration is enabled and the user is not logged in.
Broken in d71599cc7083d753d34b70ed9db9a454667f9662.
> Fix logic for 'Log in to Reply' button

- inc/write-api.php
- modules/post-actions/load.php
> Don't show comment action links if a user can't edit the comment

- inc/tpl/comment-edit.php
- inc/tpl/comment.php
- js/views/comment.js
> Don't use the `userLogin` of the current logged in user when checking for anonymous comment authors.

- o2.php
Polldaddy also has an oembed provider and embeds under poll.fm urls. (https://core.trac.wordpress.org/browser/tags/4.6.1/src/wp-includes/class-oembed.php#L76)
This removes those, too.
> Remove second Polldaddy oembed provider

- inc/fragment.php
- inc/tags.php
* In `o2_Tags::tag_links()` cache the results of `get_term_by()` calls.
* Introduce `o2_Fragment::get_post_tags()` as a wrapper for `wp_get_post_tags()` with caching.
Related: https://meta.trac.wordpress.org/ticket/1829
> Cache term calls

- inc/terms-in-comments.php
apply_filters should take a value as the second argument, not a function handle. Current implementation just returns the literal string  "__return_true".
> Fix apply_filters bug in should_process_terms

- modules/time-shortcode/load.php
To parse a date string, o2 creates a new Date object (initialized to the current time) then sets that Date object's year, day, month, hour, minute, and second (in that order) according to the value of the string.
If the desired date's day of the month is larger than the current month's last day, the logic breaks.
```js
d = new Date( '2016-09-30T12:00:00' );
// This new Date object (initialized not to the current time as in
// the bug but to a convenient time that demonstrates the bug)
// We now want to set `d` to October 31st, 2016
// Set the year...
d.setUTCFullYear( 2016 )
// no change
// Set the day...
d.setUTCDate( 31 );
// The month is still September, so we're trying to set the date to
// September 31st, which doesn't exist. JS will overflow and set the date
// to October 1st
// Set …
```
> Time Shortcode: Fix JS Date Parsing During Short Months

- tests/phpunit/test-o2-base.php
There was a race-condition in the insert_comment_actions test where
a test would fail if the second changed between the start and finish
of the test. (https://travis-ci.org/Automattic/o2/jobs/165872181)
I have modified the test to handle up to 1 full second of difference
in the checking. This should resolve that condition, and if the test
takes longer than a second something has gone horribly wrong somewhere
and we'd probably want to know that it takes over a second to insert
a comment anyways.
> Allow up to 1-second difference in insert_comment_actions test.

- inc/fragment.php
- js/app/main.js
- js/collections/users.js
- js/models/user.js
This fixes issue #16.
Users with e-mails as usernames would be unable to use o2-enabled sites
because jQuery selectors would get confused by the "." in their name and the site would break.
I've modified the plugin to use user nicenames for classes and selectors,
which should give class names and selections that won't break anything.
It seems like this may have been attempted before or regressed some time ago, because there were
some references in main.js to nicenames but nothing involving nicenames anywhere else. I've also fixed those to work correctly.
> Use nicenames in classes and selectors

- modules/time-shortcode/js/time-shortcode.js
- modules/time-shortcode/load.php
- phpunit.xml.dist
- tests/phpunit/modules/test-time-shortcode.php
- tests/qunit/index.html
- tests/qunit/modules/time-shortcode.js
I've refactored the time shortcode module to make it more robust and unit-testable, as well as unit testing the module.
I've also set up a basic QUnit implementation to enable testing of the time shortcode module javascript and other javascript from the plugin.
> Time shortcode refactor and QUnit set up

- modules/unreplied-posts/load.php
`get_query_var()` requires that the global `$wp_query` is set up.
Fixes #120.
> Unreplied Posts: Prevent a fatal error if main query isn't available yet

- modules/sticky-posts/load.php
Noticed this on WordPress.org where handbook pages currently have a sticky action.
> Show sticky posts actions only for posts

- inc/tpl/comment-edit.php
- inc/tpl/comment.php
- inc/tpl/logged-out-create-comment.php
- inc/tpl/post-edit.php
- inc/tpl/post.php
- modules/live-comments/load.php
- modules/notifications/load.php
Hi, 
cc @ocean90,
**Even empty**, `alt` attribute should always be set to avoid assistive technologies to vocalize the file name. I guess we do not need to put author's name since it's always displayed close to the avatar. We do not need to use alt texts like "avatar" because this provide no information for the user of AT.
See Andrea's issue opened in meta.trac.w.org here: https://meta.trac.wordpress.org/ticket/3371
This patch was tested on a local instance of o2. Seems to fix the issue.
Cheers,
Jb
> add missing alt attribute to avatars

- modules/time-shortcode/js/time-shortcode.js
- modules/time-shortcode/load.php
- tests/qunit/modules/time-shortcode.js
For more elaborate usages of the `[time]` shortcode I'd like to add an attribute format which can be
```
[time]Dec 18 15:00 UTC[/time] == [time format=full]Dec 18 15:00 UTC[/time]
→ Monday, December 18, 2017 16:00 UTC+1
[time format=time]Dec 18 15:00 UTC[/time]
→ 16:00 UTC+1
[time format=date]Dec 18 15:00 UTC[/time]
→ Monday, December 18, 2017
[time format=shortdate]Dec 18 15:00 UTC[/time]
→ December 18, 2017
```
> Add support to format the displayed time

- inc/fragment.php
The data attribute `data-item-text` tries to store the content of the
checklist item, but if the content contains html, then the result is that
malformed html is generated.
This strips the tags from the html before encoding it in the data
attribute.
Before:
After:
Fixes #123 
It appears that the reason for storing the content is to allow it to be used [when editing](https://github.com/Automattic/o2/blob/81f7ed8672e197174a8f91f475c18084fb3d968b/modules/checklists/js/views/common.js#L134) the checklist item. I suppose this change might break that flow, since it would erase the html, but that probably needs to be refactored to work differently for safe manipulation of html and I think this bug fix is more important than preserving that behavior.
> CheckList: strip tags from data stored in item-text attribute

- js/views/post.js
- modules/post-actions/css/_post-actions.scss
- modules/post-actions/css/style.css
- o2.php
I kept clicking on this link, which takes me to the post and the window location is the full URL. I thought I'd see if I could change that behaviour so the short link is copied to the clipboard. I also added the shake animation to the icon.
I'm not sure whether the code is organised in the right way. I've added the CSS to the module, but the JS is in the main view for posts, which seems wrong. I'm happy to refactor as needed!
- On a WordPress test site install the [P2-breathe theme](https://o2app.files.wordpress.com/2018/04/p2-breathe.zip), along with the current version of the O2 plugin (clone this repo to the plugins directory).
- View the site and click on the three dot menu at the top right of a post, followed by the Shortlink option. 
- Notice that this takes you to the post as …
> Dropdown Actions: Change the short link action to being copied to the clipboard

- inc/tags.php
o2 would like there to be only one source of and storage for tags: the post and comments' contents via #inline-tags.
To integrate with the rest of the world, though, o2 currently tries to accommodate tags submitted via wp-admin/ (Classic Editor, Quick Edit, and the Bulk Post Editor) by checking for various `$_POST` and `$_GET` keys.
These limited checks, however, mean that o2 does not currently accommodate tags submitted through REST API requests; these tags get overwritten by o2's tag processing.
Instead of looking for wp-admin/ requests and handling them specially, let's flip the logic around and handle o2 write requests specially:
* For o2 write requests, overwrite any existing tags with those found in #inline-tags.
* For any other requests, append the #inline-tags to the existing set …
> Fix Tag Processing for Posts Updated via the REST API

- o2.php
The title says it all, removes the `continue;` from within the switch.
Using a continue there is equivalent to break, and latest PHP is issuing a warning.
> Remove continue, throws warning in latest PHP and equivalent to break

- js/utils/post-action-states.js
Stateful buttons using the `PostActionStates` system have a `data-actionstate` attribute on them in the DOM. There was a bug (omission?) that prevented this attribute from being updated dynamically, so once changed the value would be wrong until page reload. This is not ideal for theme CSS that relies on this attribute to determine state.
This omission is possibly due to a gotcha in [jQuery `.data()`](https://api.jquery.com/data/), where it doesn't do anything about `data-*` attributes:
> Using the `data()` method to update data does not affect attributes in the DOM. To set a `data-*` attribute value, use `attr`.
I think we can keep the original `data()` call for now because some parts of the code still rely on that being there. (Maybe we should migrate everything to `.attr( 'data-*' )` …
> Update `data-actionstate` on buttons

- o2.php
Jetpack_User_Agent_Info's is_tablet() method is no longer static as of Jetpack 8.7. Introduced in [this change](https://github.com/Automattic/jetpack/pull/16129/files#r451102718). 
As of Jetpack 8.7, this will actually fatal sites running Jetpack 8.7. 
We have a [PR](https://github.com/Automattic/jetpack/pull/16430) which patches this on the Jetpack side, but it should be updated here as well. 
This PR works in both versions of the method.
> Jetpack compatibility: Update is_tablet() to use public method

- js/utils/timestamp.js
Fixes #226 
With the date_format being set to `j \d\e F \d\e Y`...
| | Before | After |
| --- | --- | --- |
| UI | <img width="289" alt="Screenshot 2023-06-16 at 12 45 42 pm" src="https://github.com/Automattic/o2/assets/767313/9c309b37-4a09-423d-9d0c-c18bb03696c6"> | <img width="195" alt="Screenshot 2023-06-16 at 12 55 20 pm" src="https://github.com/Automattic/o2/assets/767313/b608d75d-1345-4f63-96eb-7a2d6f9c0b10"> |
| Moment.JS string | `D[ ][\]DD[\]Z[ ]MMMM[ ][\]DD[\]Z[ ]YYYY` | `D[ ][d][e][ ]MMMM[ ][d][e][ ]YYYY` |
> Support PHP Escaped characters

- modules/to-do/load.php
Use `wp_parse_list()` to handle array-like inputs, to avoid PHP Warnings.
```
E_WARNING: explode() expects parameter 2 to be string, array given
```
Upstreaming this change that I made to the WordPress.org version of o2 back on 2024-04-24.
Looks like this was triggered by something like this:
```
GET https://example.org/p2/2024/04/24/post-name-here/?tags[]=junk
```
> Todo module: Avoid PHP Warnings

- modules/notifications/js/app/notifications.js
I don't really know why this happens, but `ready.o2` fires after `preload.o2`, but the `ready.o2` hook is fired before the `preload.o2` hook has run too.
I assume this is because o2 is assuming that `ready.o2` is unique to o2, but actually it's just a namespaced variant of `ready`, so document ready triggers it, and then o2 triggers it.
```
15:20:23.374 notifications.js?ver=6.5-beta2-57697:81 ready.o2 without notifs
15:20:23.403 notifications.js?ver=6.5-beta2-57697:76 preload.o2
15:20:23.432 notifications.js?ver=6.5-beta2-57697:81 ready.o2 with notifs
```
Fixes #225
> Notifications: Don't load if not loaded
