Automattic/o2

js/collections/users.js
Reverts Automattic/o2#33
Pending some more testing.
=> Revert "Changed modelClass to use hash instead of userLogin."

modules/sticky-posts/load.php
=> Use 'edit_others_posts' capability for (un)sticking posts.

inc/fragment.php, modules/to-do/inc/class-to-do-widget.php
=> Pass the post ID as the second argument to the `the_title` filter.

inc/template-tags.php
=> Use `delete_post` capability for post trash action.

inc/xposts.php, o2.php
=> Add o2::is_enabled() and replace wpcom_o2_is_enabled() calls with it.

tests/phpunit/test-terms-in-comments.php
Baseline unit test coverage for the o2_Terms_In_Comments class.
=> Unit tests

css/src/ui/_editor.scss, css/style.css
=> Editor: Add cleafix for editor footer

css/src/ui/_editor.scss, css/style.css, inc/tpl/comment-edit.php, inc/tpl/front-side-new-post-edit.php, inc/tpl/post-edit.php
=> Editor: Use a specific CSS class for editor tabs.

js/utils/keyboard.js
=> Add missing semicolons.

modules/to-do/inc/class-to-do-widget.php
=> ToDo Widget: Fix post query in `o2_ToDos_Widget::fetch()`

js/editor/editor.js, o2.php
=> Editor: Use current site ID as cache prefix

modules/to-do/js/views/widget.js
=> ToDo widget: Avoid simultaneous requests by `o2.Views.ToDosWidget.fetchAll()`

inc/tpl/comment-edit.php, inc/tpl/front-side-new-post-edit.php, js/views/comment.js, js/views/new-post.js, o2.php
=> Add `o2_post_form_before` and `o2_comment_form_before` filters

js/views/new-post.js
=> Editor: Allow to filter new post data before it's saved.

js/editor/editor.js
=> Editor: Add missing site ID to cache key.

modules/post-actions/load.php
A write request is also kind of a read request because it returns the data of the new post.
Fixes #108.
=> Add post actions during write requests

inc/fragment.php, tests/phpunit/test-fragment.php
This should be a good baseline unit test coverage for the o2_Fragment class.
=> o2_Fragment unit tests

css/src/ui/_editor.scss, css/style-rtl.css, css/style.css, js/editor/editor.js
This gives a much smoother scrolling experience.
Support is looking good since two days ago:
http://caniuse.com/#feat=css-sticky
=> Use position sticky for editor toolbar when available

modules/to-do/inc/class-to-do-widget.php
The To Do widget shouldn't show pending or future posts.
cc: @pento
=> Show only published and private posts in a To Do widget

js/utils/uuid4.js, o2.php
Handy for things like clientside uid.
=> Add uuidv4 utility

.travis.yml, js/utils/uuid4.js, phpunit.xml.dist
See my struggle in the commits.
=> Make CI go green

.gitignore, inc/read-api.php
Check if user has capability to edit posts before allowing them to preview a post.
=> Add preview acess check

inc/write-api.php
Add more defensive checks for identifiers passed to create/update api endpoints for post/comment.
=> Add defensive checks
